title: Rodrigues, Felipe.
email: fr.costa95@gmail.com
description: My resume on-line.
baseurl: ""
url: ""
twitter_username: frodrigues95
github_username:  RodriguesLs
linkedin_username: Rodrigues

# Build settings
markdown: kramdown
permalink: /:title
# paginate: 3
theme: minima
plugins:
  - jekyll-feed
include:
  - _pages